### ISSUE TITLE
GitHub Releases still indicate that version 0.13 is the latest release

### ISSUE THREAD

**Issue by rodikal** [vandmo/dependency-lock-maven-plugin#42]
The "Releases" info on the main GitHub page is indicating that the latest release is version 0.13.
However several versions have been released since then, so it would be interesting to update that information.

**Comment by vandmo** [comment]
Good point.
Everything is released through GitHub Actions to Maven Central, including the source code so the releases in GitHub doesn't really make sense. I have removed the old releases but would be nice to find a way to indicate what the current versions is without having to edit the README after each release.

**Comment by vandmo** [comment]
Found: https://img.shields.io/maven-central/v/se.vandmo/dependency-lock-maven-plugin which seems to work well.
Added that to README.md, seems to work.
