### ISSUE TITLE
Support patterns for ignore, and my version, lists

### ISSUE THREAD

**Issue by danielhodder** [vandmo/dependency-lock-maven-plugin#61]
In my project we have ~130 modules which make up the project, these all have inter-dependencies on each other. Rather than listing all of these modules out it would be good if we could use a pattern to ignore all of the dependencies in the groups that we are happy to have floating.

As far as I can this would 'just' involve changing the `StrictPatternIncludesArtifactFilter` to a `PatternIncludesArtifactFilter` in the `check` Mojo.

Would this be something you'd accept?

**Comment by vandmo** [comment]
I think you should already be able to achieve what you want with the strict matching. `com.mycompany:*` should work?

**Comment by danielhodder** [comment]
I had another look at my issue and it was my own fault sorry. Seems like I misread the code, and mistyped my pattern. At least on the 0.x branch this works as expected. I will test with the 1.x version once that's released in some way. If you don't get around to it I will see if I can find some time to try and fix up the builds and get the tests passing again next week.

For now I think we can safely close this and I'll reopen this, or create a new issue, if I hit further issues.

**Comment by vandmo** [comment]
Very close to a 1.0 release now. Only need to write a bunch of more tests and fix the bugs that I will find :)
Created a 0.0.df645e025a41a7aad7f306497255e232098f6e0d release which you can test which is bound to have some bugs though.

**Comment by danielhodder** [comment]
Sorry just getting around to this today. I am not seeing the `0.0.df645e025a41a7aad7f306497255e232098f6e0d` version in the central maven repo at this time. The latest version that I can see is [`0.0.78f56707b3a1d639c8e769bba1686587e9a89564`](https://search.maven.org/artifact/se.vandmo/dependency-lock-maven-plugin/0.0.78f56707b3a1d639c8e769bba1686587e9a89564/maven-plugin), which is obviously a ways back being based on `78f56707b3a1d639c8e769bba1686587e9a89564`.

**Comment by vandmo** [comment]
You are right, I forgot to preprend "release-" to the the tag when triggering a release. 0.0.0fcba43c95c016556b4ef8d51d8aee999a0c51b3 should work now though.

**Comment by danielhodder** [comment]
Tested this does indeed work as expected. In our particular environment we needed to use `<version>ignore</version>` rather than `<version>use-project-version</version>`; but it works perfectly. Loving your work, thanks so much for providing this great plugin.

**Comment by vandmo** [comment]
Thanks :)
Releasing 0.0.04d7dd844a26dcdd085a71fde56b36f1747b2cf9 now where ignoring integrity works. I decided to always include <optional>false</optional> when optional in pom lock file. So if you are using that you should create a new lock file.

Why do you need to ignore the version? Ideally you should be able to use use-project-version or something similar. I have an issue for comparing SNAPSHOT versions which I plan to fix.
