### ISSUE TITLE
Add more control over produced lock file

### ISSUE THREAD

**Issue by andruhon** [vandmo/dependency-lock-maven-plugin#77]
Since the "use-mine" feature is gone it became harder to avoid noise from subproject in multi-project set ups.

It is currently possible to partially solve this issue with setup like this
```
                        <dependencySets>
                            <dependencySet>
                                <includes>
                                    <include>com.company:my-test-subproject</include>
                                </includes>
                                <version>ignore</version>
                                <integrity>ignore</integrity>
                            </dependencySet>
                        </dependencySets>
```
This works fine, but these subprojects will keep popping up as changes in the lock file.

This would be nice to have an option for lock mojo to pick up the config and write something like that into the lock file:
```
{
    "groupId" : "com.company",
    "artifactId" : "my-test-subproject",
    "version" : "ignore",
    "scope" : "test",
    "type" : "test-jar",
    "optional" : false,
    "integrity" : "ignore",
    "classifier" : "tests"
  },
```

**Comment by vandmo** [comment]
Yes, makes sense. Might have some implications with regards to backward compatibility with the lock file. If you create the lock file with a newer version it will not be able to be parsed by older versions. Then again, it is the version of the plugin used for checking that is the easiest to control...

**Comment by vandmo** [comment]
I confirmed that `integrity: ignored` will fail on current version of the plugin.
`"integrity" : "sha512:IGNORED/IGNORED/IGNORED/IGNORED/IGNORED/IGNORED/IGNORED/IGNORED/IGNORED/IGNORED/IGNORED/"` on the other hand works with current version but seems a bit stupid.

I am leaning towards having `integrity: ignored` and `version: ignored` in the lock files but I am not sure if you should need to opt-in when creating the lock file. Without opt-in them somebody might use a never version of the plugin to create a lock file but not update the version that checks the dependencies and thus it would fail. On the other hand, that build would hopefully fail before reaching somebody else.

**Comment by andruhon** [comment]
I also have it working considering that artifact has all the ignores and the lock file edited to something like this:
```
 ...
  }, {
    "groupId" : "com.company",
    "artifactId" : "company-common",
    "version" : {
      "use-mine" : true
    },
    "version" : "use-project-version",
    "scope" : "compile",
    "type" : "jar",
    "optional" : false,
    "integrity" : "sha512:ignore",
    "classifier" : "weave"
  }, {
  ...
```

And yes it fails with older version or with ignores not configured, which I think is correct, because these values clearly would not match any possible real versions. Of course I believe this sort lock output should be optional, configurable behaviour rather than default one.

**Comment by andruhon** [comment]
Sorry pushed wrong piece of JSON initially. Updated above.

**Comment by vandmo** [comment]
I think I will go for opt-in instead.
* 100% backwards compatible
* allows people to have the old behavior if the want it
* allows for breaking change of the format

**Comment by vandmo** [comment]
@andruhon I have pushed code now that you could try out by building the plugin locally.
Will try to publish a "snapshot" version as soon as possible as well (but having some problems with that which I need to resolve)

**Comment by andruhon** [comment]
Thank you! I'll test this very soon and will let you know how it goes.

**Comment by andruhon** [comment]
I pulled the master and generated locks. At a first glance it looks really good. Thank you very much!
I'll scrutinize deps in the lock file further and will update you tomorrow.

**Comment by andruhon** [comment]
I tried this with relatively big dependencies base and it looks good. I asked other developers to have a look and they were also happy. I think it's good to be released.

**Comment by andruhon** [comment]
I created a PR to update the README https://github.com/vandmo/dependency-lock-maven-plugin/pull/78
